#!/bin/sh
# Copyright 2023 Northern.tech AS
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

set -e

STATE="$1"
FILES="$2"

temp_dir="$FILES"/tmp

cleanup() {
    set +e
    test -f "$PERSISTENT_STORE"/.rw_test && rm -f "$PERSISTENT_STORE"/.rw_test
}

trap cleanup 1 2 3 6 15

CONFIG_FILE="/etc/mender/mender-app.conf"
PERSISTENT_STORE="/data/mender-app"
APP_MODULE_DIR="/usr/share/mender/app-modules/v1"

version=""
orchestrator=""
platform=""
app_sub_module=""
artifact_name=""
application_name=""
options=""

if test -f "$CONFIG_FILE"; then
    . "$CONFIG_FILE"
fi

if test -d "$PERSISTENT_STORE"; then
    if touch "$PERSISTENT_STORE"/.rw_test; then
        rm -f "$PERSISTENT_STORE"/.rw_test
    else
        echo "ERROR: cant write to persistent_store in $PERSISTENT_STORE"
        exit 1
    fi
fi

CONFIG_HAS_XDELTA3_CMD="xdelta3"
CONFIG_HAS_TAR_CMD="tar"
delta_cmd="${CONFIG_HAS_XDELTA3_CMD} -d -s"
tar_decompress_cmd="${CONFIG_HAS_TAR_CMD} -xzvf"

assert_requirements() {
    local cmd
    local rc=0
    set +e

    if ! $CONFIG_HAS_TAR_CMD --version < /dev/null > /dev/null 2>&1; then
        echo "error: cannot find required command '${CONFIG_HAS_TAR_CMD}' in PATH." 1>&2
        rc=127
    fi
    if ! $CONFIG_HAS_XDELTA3_CMD < /dev/null > /dev/null 2>&1; then
        echo "warning: cannot find command '${CONFIG_HAS_XDELTA3_CMD}' in PATH." 1>&2
    fi
    $app_sub_module REQS
    if test $? -ne 0; then
        rc=1
    fi
    set -e
    return $rc
}

parse_metadata() {
    application_name=$(jq -r .application_name < "$1")
    platform=$(jq -r .platform < "$1")
    orchestrator=$(jq -r .orchestrator < "$1")
    version=$(jq -r .version < "$1")
    app_sub_module="${APP_MODULE_DIR}/${orchestrator}"
    if test ! -f "${app_sub_module}"; then
        echo "ERROR: ${app_sub_module} not found. exiting."
        return 1
    fi
    if test ! -x "${app_sub_module}"; then
        echo "ERROR: ${app_sub_module} not executable. exiting."
        return 1
    fi
    if test ! -r "${app_sub_module}"; then
        echo "ERROR: ${app_sub_module} not readable. exiting."
        return 1
    fi
    artifact_name=$(jq -r .artifact_provides.artifact_name < "$2")

    if test "${application_name}" = ""; then
        echo "ERROR: application_name is required. exiting."
        return 1
    fi

    if test "${platform}" = ""; then
        echo "ERROR: platform is required. exiting."
        return 1
    fi

    if test "${orchestrator}" = ""; then
        echo "ERROR: orchestrator is required. exiting."
        return 1
    fi

    if test "${version}" = ""; then
        echo "ERROR: version is required. exiting."
        return 1
    fi

    if test "${artifact_name}" = ""; then
        echo "ERROR: artifact_name is required. exiting."
        return 1
    fi
}

handle_artifact() {
    local image_dir
    local image
    local url_new
    local url_current
    local sha_new
    local sha_current
    local image_current
    local image_new
    local deep_delta
    local rollback_id="last"

    if test ! -d "$temp_dir"; then
        echo "ERROR: temp_dir does not exist"
        return 1
    fi

    $tar_decompress_cmd "$1"/images.tar.gz -C "$temp_dir"
    $tar_decompress_cmd "$1"/manifests.tar.gz -C "$temp_dir"

    for image_dir in "${temp_dir}/images/"*; do
        url_new=$(cat "${image_dir}/url-new.txt")
        url_current=$(cat "${image_dir}/url-current.txt")
        sha_new=$(cat "${image_dir}/sums-new.txt")
        sha_current=$(cat "${image_dir}/sums-current.txt")
        if test "$url_new" = ""; then
            echo "ERROR: payload ${image_dir}/url-new.txt cannot be empty"
            return 1
        fi
        if test "$sha_new" = ""; then
            echo "ERROR: sha_new cannot be empty"
            return 1
        fi

        if test "$url_new" != "$url_current"; then
            if test "$url_current" = ""; then
                echo "ERROR: url_current cannot be empty"
                return 1
            fi
            if test "$sha_current" = ""; then
                echo "ERROR: sha_ccurrent cannot be empty"
                return 1
            fi
            if test ! -f "${image_dir}/deep_delta"; then
                # deep-delta means that the binary delta was generated at the layers level,
                # and the orchestrators submodule will deal with decoding during the LOAD below
                # ref. to LOAD implementations
                image_current="${temp_dir}/current.${sha_current}.img"
                image_new="${temp_dir}/new.${sha_new}.img"
                $app_sub_module SAVE "${application_name}" "$url_current" "$image_current"
                $delta_cmd "$image_current" "${image_dir}/image.img" "${image_new}"
                mv -v "${image_new}" "${image_dir}/image.img"
            fi
        fi
    done
    for image_dir in "${temp_dir}/images/"*; do
        url_current=$(cat "${image_dir}/url-current.txt")
        url_new=$(cat "${image_dir}/url-new.txt")
        sha_new=$(cat "${image_dir}/sums-new.txt")
        deep_delta=""
        if test -f "${image_dir}/deep_delta"; then
            deep_delta=deep_delta
        fi
        MODULE_TMPDIR="${temp_dir}" OPTIONS="${deep_delta}" $app_sub_module LOAD "${application_name}" "${url_new}" "${image_dir}/image.img" "${url_current}"
        # and the sub module deals with proper image loading
    done
    # we should check if the app is healthy and alive, then decide what to do
    # at the moment we assume it is alive and ok
    if test -d "${PERSISTENT_STORE}/${application_name}-${rollback_id}"; then
        rm -Rf "${PERSISTENT_STORE}/${application_name}-${rollback_id}"
    fi
    if test -d "${PERSISTENT_STORE}/${application_name}/"; then
        mv -v "${PERSISTENT_STORE}/${application_name}/" "${PERSISTENT_STORE}/${application_name}-${rollback_id}"
        $app_sub_module STOP "${application_name}" "${PERSISTENT_STORE}/${application_name}-${rollback_id}/manifests"
    fi
    mkdir -p "${PERSISTENT_STORE}/${application_name}"
    mv -v "$temp_dir/manifests" "${PERSISTENT_STORE}/${application_name}/"
    $app_sub_module ROLLOUT "${application_name}" "${PERSISTENT_STORE}/${application_name}/manifests"
    # now if $app_sub_module healthy then rm -Rf "${PERSISTENT_STORE}/${artifact_name}-${rollback_id}"
    # and on rollback we just deploy "${PERSISTENT_STORE}/${artifact_name}-${rollback_id}"
    # earlier ln -s "${PERSISTENT_STORE}/${artifact_name}-${rollback_id}" "${PERSISTENT_STORE}/${artifact_name}-rollback"
    # and removing all else
}

case "$STATE" in

    NeedsArtifactReboot)
        echo "No"
        ;;

    SupportsRollback)
        echo "No" # switch to Yes on MEN-6077
        ;;

    ArtifactInstall)
        parse_metadata "$FILES"/header/meta-data "$FILES"/header/header-info
        assert_requirements
        rc=$?
        if test $rc -ne 0; then
            exit $rc
        fi
        handle_artifact "$FILES"/files
        ;;

    ArtifactRollback)
        true
        ;;

esac
